experiment: volga2k_unsupervised
save_dir: experiments
resume: True
accelerator: 'gpu'

model:
  type: cycle_cm_kan
  params:
    in_dims:
      - 3
    out_dims:
      - 3
    grid_size: 5
    spline_order: 3
    residual_std: 0.1
    grid_range:
      - 0.0
      - 1.0

data:
  type: volga2k_unpaired
  train:
    source: 'data/volga2k/train/source'
    target: 'data/volga2k/train/target'
  val:
    source: 'data/volga2k/val/source'
    target: 'data/volga2k/val/target'
  test:
    source: 'data/volga2k/test/source'
    target: 'data/volga2k/test/target'

pipeline:
  type: unsupervised
  params:
    lr: 1e-3
    batch_size: 2
    val_batch_size: 6
    test_batch_size: 6
    epochs: 500
    save_freq: 10
    visualize_freq: 10
    pretrained: True
    pretrained_model: 'experiments/volga2k_unsupervised_pretrain/logs/checkpoints/last.ckpt'
